# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07a3599743fde7025d38a266cc3bbfd31c760044e1cc13ea0653f0ab99f4a7906b5af0e5cec942b42ed40a355c259b502975f0c6facf65bb32f7183ae1d55f01

test:
  secret_key_base: 3763a7df8c9b734c047971295bb01f7ace09a9be7918a15e4aa2528e9f59022e972748908a676aafc2850f43bba42574753b0a0d061c65aab1c0bee8daa97d10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
